# Generated by Django 4.2 on 2023-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice_field',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], max_length=2),
        ),
    ]
